name: Build on Ubuntu with default options

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: ./buildconf && ./configure
    - name: make
      run: make
    - name: make check
      run: make test-nonflaky
