name: 🐞 Bug Report
description: File a report to help us improve Etterna!
title: "[Bug]: "
labels: ["Type: Bug", "Needs triage"]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report! Please make sure to check if the bug has already been reported before submitting a new report.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com, Discord#1234, Just reply to the issue...
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Version Info
      description: What version of Etterna are you running?
      options:
        - Latest available release
        - Compiled from develop
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux (any distro)

  - type: textarea
    attributes:
      label: Bug Behavior
      description: Describe the bug you're currently experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: What steps should we follow to see the bug?
      placeholder: |
        1. Run the game
        2. Select "Game Start"
        3. Open the debug menu
        4. '...'

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false