name: 🛠️ Feature Request
description: Share your ideas on how to improve the game!
title: "[Feature Request]: "
labels: ["Type: Enhancement"]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for the feature?
      description: Please search to see if an issue already suggested the feature you're thinking.
      options:
        - label: I have searched the existing feature requests
          required: true

  - type: textarea
    attributes:
      label: Describe the Feature
      description: What is the addition you are proposing?
    validations:
      required: true

  - type: textarea
    attributes:
      label: How Does The Feature Add To The Game?
      description: (Explain the problem the feature aims to solve, or the new things it allows)
      placeholder: |
        In Etterna, it was previously not possible to ...
        However, this feature lets players ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: |
        If you have any background information that would help implement the feature, put it here.
        (e.g. knowing which section of the code would have to be changed, or describing how another game implemented a similar thing)
    validations:
      required: false