version: 2.0
jobs:
  build:
    docker:
      - image: sergiusthebest/rtems-arm-rasberrypi-ci:latest
    steps:
      - checkout
      - run: cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE && cd build && make -j