language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    packages:
      - gobjc++

script:
  - cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cd build
  - make