name: Manual

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fix stupidity
      run: |
        cp AUTHORS AUTHORS.
        cp LICENSE LICENSE.
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: manual
        root_file: tracy.tex
    - uses: actions/upload-artifact@v2
      with:
        name: manual
        path: manual/tracy.pdf
